# Generated by Django 5.0.1 on 2024-02-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_preregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='user',
        ),
    ]
